// Generated by gencpp from file open_manipulator_msgs/ArmToCar.msg
// DO NOT EDIT!


#ifndef OPEN_MANIPULATOR_MSGS_MESSAGE_ARMTOCAR_H
#define OPEN_MANIPULATOR_MSGS_MESSAGE_ARMTOCAR_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace open_manipulator_msgs
{
template <class ContainerAllocator>
struct ArmToCar_
{
  typedef ArmToCar_<ContainerAllocator> Type;

  ArmToCar_()
    : start_time()
    , move(false)
    , forward_state(false)  {
    }
  ArmToCar_(const ContainerAllocator& _alloc)
    : start_time()
    , move(false)
    , forward_state(false)  {
  (void)_alloc;
    }



   typedef ros::Time _start_time_type;
  _start_time_type start_time;

   typedef uint8_t _move_type;
  _move_type move;

   typedef uint8_t _forward_state_type;
  _forward_state_type forward_state;





  typedef boost::shared_ptr< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> const> ConstPtr;

}; // struct ArmToCar_

typedef ::open_manipulator_msgs::ArmToCar_<std::allocator<void> > ArmToCar;

typedef boost::shared_ptr< ::open_manipulator_msgs::ArmToCar > ArmToCarPtr;
typedef boost::shared_ptr< ::open_manipulator_msgs::ArmToCar const> ArmToCarConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::open_manipulator_msgs::ArmToCar_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::ArmToCar_<ContainerAllocator2> & rhs)
{
  return lhs.start_time == rhs.start_time &&
    lhs.move == rhs.move &&
    lhs.forward_state == rhs.forward_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::open_manipulator_msgs::ArmToCar_<ContainerAllocator1> & lhs, const ::open_manipulator_msgs::ArmToCar_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace open_manipulator_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4b7661ede9092fffae22ae49adf1666d";
  }

  static const char* value(const ::open_manipulator_msgs::ArmToCar_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4b7661ede9092fffULL;
  static const uint64_t static_value2 = 0xae22ae49adf1666dULL;
};

template<class ContainerAllocator>
struct DataType< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "open_manipulator_msgs/ArmToCar";
  }

  static const char* value(const ::open_manipulator_msgs::ArmToCar_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time start_time\n"
"bool move\n"
"bool forward_state\n"
;
  }

  static const char* value(const ::open_manipulator_msgs::ArmToCar_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start_time);
      stream.next(m.move);
      stream.next(m.forward_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmToCar_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::open_manipulator_msgs::ArmToCar_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::open_manipulator_msgs::ArmToCar_<ContainerAllocator>& v)
  {
    s << indent << "start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start_time);
    s << indent << "move: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.move);
    s << indent << "forward_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.forward_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPEN_MANIPULATOR_MSGS_MESSAGE_ARMTOCAR_H
